name: Tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Build
        env:
          IS_GITHUB_ACTION: true
        run: |
          mkdir res && cd astra && RUSTFLAGS='-C link-arg=-s' cargo build --target wasm32-unknown-unknown --release
          cd .. && cp target/wasm32-unknown-unknown/release/astra.wasm res/
      - name: Build
        env:
          IS_GITHUB_ACTION: true
        run: cargo build --workspace --target wasm32-unknown-unknown --release
      - name: Wasm copy
        run: cp target/wasm32-unknown-unknown/release/*.wasm res/

      - name: Run Cargo tests
        env:
          IS_GITHUB_ACTION: true
        run: cargo test --workspace -- --nocapture
      # - name: Run Ava tests
      #   env:
      #     IS_GITHUB_ACTION: true
      #   run: cd astra && sh test.sh
