name: Tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Build
        env:
          IS_GITHUB_ACTION: true
        run: cd astra
        run: cargo build --release --target wasm32-unknown-unknown
      - name: Wasm copy and strip
        run: |
          find target/wasm32-unknown-unknown/release \
            -maxdepth 1 \
            -name \*.wasm \
            -prune \
            -exec cp {} res \;
          for f in res/*.wasm
          do
            wasm-opt -Oz -o "$f" "$f"
          done 
      - name: Build
        env:
          IS_GITHUB_ACTION: true
        run: cargo +stable build --workspace --target wasm32-unknown-unknown --release
      - name: Run Cargo tests
        env:
          IS_GITHUB_ACTION: true
        run: cargo test --workspace -- --nocapture
      - name: Run Ava tests
        env:
          IS_GITHUB_ACTION: true
        run: cd astra && sh test.sh
